ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Produits:produits }
    
ecommerce_produit:
    path:     /produit/{id}
    defaults: { _controller: EcommerceBundle:Produits:produit }
    
ecommerce_panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }
    
    
ecommerce_livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

ecommerce_validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }
    
categorieProduits:
    path:     /categorie/{categorie}
    defaults: { _controller: EcommerceBundle:Produits:produits }
    

rechercheProduits:
    path:     /recherche
    defaults: { _controller: EcommerceBundle:Produits:rechercheTraitement }


ajouter:
    path:     /ajouter/{id}
    defaults: { _controller: EcommerceBundle:Panier:ajouter}
    
supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimer }
    
supprimmerAdresseLivraison:
    path:     /supprimmerAdresseLivraison/{id}
    defaults: { _controller: EcommerceBundle:Panier:supprimmerAdresseLivraison }
    
    
    