services:
#    ecommerce.example:
#        class: Ecommerce\EcommerceBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
  tva:
    class: Ecommerce\EcommerceBundle\Twig\Extension\TvaExtension
    tags:
      - { name: twig.extension }