<?php

namespace Ecommerce\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * produitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function byCategorie($categorie) {
        $qb = $this->createQueryBuilder('produit')
            ->select('produit')
            ->where('produit.categorie = :categorie')
            ->andWhere('produit.disponible = 1')
            ->orderBy('produit.id')
            ->setParameter('categorie',$categorie);
        
        return $qb->getQuery()->getResult();
    }
    
    public function recherche($chaine) {
        $qb = $this->createQueryBuilder('produit')
            ->select('produit')
            ->where('produit.nom like :chaine')
            ->andWhere('produit.disponible = 1')
            ->setParameter('chaine', $chaine.'%');
        
        return $qb->getQuery()->getResult();
    }

    public function findArray($array) {
        $qb = $this->createQueryBuilder('produit')
            ->select('produit')
            ->where('produit.id IN (:array)')
            ->setParameter('array', $array);

        return $qb->getQuery()->getResult();
    }
}
